-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE NOT ANIMAL_ID 
IN (SELECT INS.ANIMAL_ID 
 FROM ANIMAL_INS AS INS 
    INNER JOIN ANIMAL_OUTS AS OUTS 
    ON INS.ANIMAL_ID = OUTS.ANIMAL_ID) 
ORDER BY ANIMAL_ID;
