-- 코드를 작성해주세요
SELECT QUARTER, COUNT(QUARTER) AS ECOLI_COUNT
FROM (SELECT
 CASE 
    WHEN DATE_FORMAT(DIFFERENTIATION_DATE, "%m") BETWEEN 01 AND 03 THEN '1Q'
    WHEN DATE_FORMAT(DIFFERENTIATION_DATE, "%m") BETWEEN 04 AND 06 THEN '2Q'
    WHEN DATE_FORMAT(DIFFERENTIATION_DATE, "%m") BETWEEN 07 AND 09 THEN '3Q'
    WHEN DATE_FORMAT(DIFFERENTIATION_DATE, "%m") BETWEEN 10 AND 12 THEN '4Q'
END AS QUARTER
FROM ECOLI_DATA) AS Q
GROUP BY QUARTER
ORDER BY QUARTER
 ;