-- 코드를 입력하세요
SELECT NAME , DATETIME
FROM ANIMAL_INS
WHERE NOT ANIMAL_ID IN 
    (SELECT INS.ANIMAL_ID
     FROM ANIMAL_INS AS INS
        INNER JOIN ANIMAL_OUTS AS OUTS
        ON INS.ANIMAL_ID = OUTS.ANIMAL_ID)
ORDER BY DATETIME
LIMIT 3
;