-- 코드를 작성해주세요
SELECT E.YEAR AS YEAR, M.MAXIMUM-E.SIZE_OF_COLONY AS YEAR_DEV, E.ID AS ID
FROM 
(SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, SIZE_OF_COLONY, ID
FROM ECOLI_DATA) AS E
INNER JOIN 
(SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAXIMUM
FROM ECOLI_DATA
GROUP BY YEAR) AS M
    ON E.YEAR = M.YEAR
ORDER BY YEAR, YEAR_DEV
;
;